## 46. 제너레이터와 async/await

제너레이터는 코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개할 수 있는 특수한 함수다.

1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.
2. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.
3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.

### 제너레이터 함수의 정의

제너레이터 함수는 `function*` 키워드로 선언한다.
그리고 하나 이상의 yield 표현식을 포함한다.

### 제너레이터 객체

제너레이터 함수를 호출하면 일반 함수처럼 함수 코드 블록을 실행하는 것이 아니라 제너레이터 객체를 생성해 반환한다.
제너레이터 함수가 반환한 제너레이터 객체는 이터러블이면서 동시에 이터레이터다.

제너레이터 객체는 next 메서드를 갖는 이터레이터이지만 이터레이터에는 없는 return, throw 메서드를 갖는다.

- next: 제너레이터 함수의 yield 표현식까지 코드 블록을 실행하고
  yield된 값을 value 프로퍼티 값으로, false를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.
- return: 인수로 전달받은 value 프로퍼티 값으로, true를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.
- throw: 인수로 전달받은 에러를 발생시키고 undefined를 value 프로퍼티 값으로, true를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.

### 제너레이터의 일시 중지와 재개

제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.
제너레이터 객체의 next 메서드를 호출하면 제너레이터 함수의 코드 블록을 yield 표현식까지 실행한다.

yield 키워드는 제너레이터 함수의 실행을 일시 중지시키거나
yield 키워드 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환한다.

이터레이터의 next 메서드와 달리 제너레이터 객체의 next 메서드에는 인수를 전달할 수 있다. **전달한 인수는 yield 표현식을 할당받는 변수에 할당된다.**

```js
function* getFunc() {
  // 할당문의 연산 순서는 오른쪽에서 왼쪽이다.
  // 처음 next를 호출하면 yield 표현식까지 실행된다.
  // 두 번째 next 메서드를 호출할 때 전달되는 인수 10이 x에 할당된다.
  const x = yield 1;

  const y = yield x + 10;

  yield x + y;
}

const generator = getFunc();

// 처음 호출하는 next 메서드에는 인수를 전달하지 않는다.
let res = generator.next(); // {value: 1, done: false}

// next 메서드에 인수로 전달한 10은 첫 번째 yield 표현식을 할당받는 변수 x에 할당된다.
res = generator.next(10); // {value: 20, done: false}

// next 메서드에 인수로 전달한 20은 두 번째 yield 표현식을 할당받는 변수 y에 할당된다.
res = generator.next(20);
```

이처럼 제너레이터 함수는 next 메서드와 yield 표현식을 통해 함수 호출자와 함수의 상태를 주고받을 수 있다.
next 메서드를 통해 yield 표현식까지 함수를 실행시켜 제너레이터 객체가 관리하는 상태를 꺼내올 수 있고,
next 메서드에 인수를 전달해서 제너레이터 객체에 상태를 밀어넣을 수 있다.

### async/awiat

**async**

- 함수 앞에 사용하는 키워드
- 함수 안에 비동기적으로 실행될 부분이 있음을 알 수 있다.

**await**

- async 함수 안에서만 사용할 수 있는 키워드
- 반드시 Promise 객체 앞에서 사용한다.
- Promise 객체가 fulfiled 될 때까지 기다렸다가 상태 결과값을 추출하여 리턴한다.

async 함수 내에서 await을 만나게 되면 다음과 같이 실행된다.

**async/await의 실행 흐름**

1. await 뒤 코드가 실행되어 Promise 객체가 반환된다.
2. 코드의 실행 흐름이 async 함수를 호출한 곳(함수 바깥)으로 이동한다.
3. 콜스택이 비어있고 이전 Promise가 fulfiled 상태가 되면 상태 결과값이 추출되고, async 함수 내 다음 줄이 실행된다.

**Promise 객체의 상태가 rejected가 되면?**

rejected된 부분을 처리해주지 않는다면 `Uncaught Error`가 발생하며 코드 실행이 중단된다.
함수 전체를 try catch 문으로 감싸 이를 해결할 수 있다.

```js
async function doSomething() {
  try {
    const response = await fetch("url");
    const result = await response.text();
    console.log(result);
  } catch (error) {
    console.error(error);
  } finally {
    console.log("exit");
  }
}

doSomething();
```
